### PR TITLE
make ReadTheOrg responsive

### LINKED ISSUE #25: Better mobile support for ReadTheOrg
Right now, on a narrow screen the TOC on the left simply covers up the text body. On my Android phone this actually renders the page completely unreadable. The width of the TOC ends up taking the majority of the screen, and I can't read any of the text. I also can't zoom in or out.

On the actual [RTD theme](https://github.com/snide/sphinx_rtd_theme) it automatically switches to a mobile view as the window narrows below a certain pixel value. It seems that the `@media` `max-width` calls are in the `readtheorg.css` file, but things aren't behaving properly.

Sorry to submit a complaint rather than a PR :-1: for me.

### PR DESCRIPTION
**Pull request by geekplux**
Support mobile screen for ReadTheOrg.
The appearance after change you could refer to:

- [GeekPlux's Wiki](http://geekplux.com/wiki/)
- [Master Emacs in 21 Days](http://book.emacs-china.org)

fix #25

### CODE REVIEW

**Comment by geekplux** [comment]
preview

**Comment by fniessen** [comment]
I have integrated 99% of your changes. But I've changed a little bit colors and positions, and have update the source document (this is "literate programming"!)...

Thanks a lot for this wonderful addition -- which was missing for long!

**Comment by fniessen** [comment]
PS- You could (maybe) be interested by Emacs-Leuven, my shareable Emacs configuration file, which dramatically improves Emacs with much better defaults. At least if you're not that bound to Vim ;-)

**Comment by geekplux** [comment]
Hi, you integrated my code but close my PR…why not merge it directly and change something based on it. PR closed means my code could not be used in the repo, but now it is used in fact…

**Comment by fniessen** [comment]
OK, that's right. I've clearly stated that the integrated code was yours, though.

If you want, I can do a revert, and do it properly then.

**Comment by geekplux** [comment]
please do it though it is very trouble for you.
thanks.

**Comment by geekplux** [comment]
excuse me? @fniessen

**Comment by fniessen** [comment]
I'll do it in the coming days. Just didn't get the time yet.

**Comment by fniessen** [comment]
Done. Thanks.

**Comment by geekplux** [comment]
Thanks very very much.

**Pull request merged**
