### PR TITLE
fix table and contents overlaps on mobile

### PR DESCRIPTION
**Pull request by fliar**
margin-left seems not working on ios safari nor android chrome

### CODE REVIEW

**Comment by fniessen** [comment]
With your change, the TOC overlaps the contents -- tested on Edge.

Pull the new version (now with TOC hidden when window is too small) and check whether something still has to be done or not. Thanks!

**Comment by fliar** [comment]
hi, i've checked the latest readtheorg, it's better on my android phone,  but is there a way i can show the table of contents again?
btw on desktop ff the bottom of toc overlaps the postamble div, which hides toc scrollbar, i dont like that, personaly:).

**Comment by fliar** [comment]
i change it myself simply like this:
~~~ css
#table-of-contents{
    position:fixed;
    width:23%;
    overflow-x:hidden;
    overflow-y:auto;
    height:83%;
}
~~~

**Comment by fniessen** [comment]
Not sure to understand the real problems you're trying to show, neither the solution...

See the results of trying your settings: http://screencast.com/t/yiT6UYT8...

I don't see any improvement. But maybe we're talking of different things or contexts. Could you elaborate with "before/after pictures"?  Thanks.

**Comment by fliar** [comment]
you got a large screen! :)
in my case, table of content and postamble will overlap like this:
[https://github.com/fliar/fliar.github.io/blob/master/pic/2016/Screenshot20160824115925.png](url)
that's the reason i use percentage

**Comment by fniessen** [comment]
That's how the default overlap is, right?

If you want to show me the results of your commit, could you show me how it is before applying it, and how it is after applying it.

Regarding my screen, I do now have a 4K monitor. Before, I was working on a Full HD (1920x1080).

**Comment by fliar** [comment]
i set height to percentage because i don't want the postamble div hide the table of content, this is 87% setting:

https://raw.githubusercontent.com/fliar/fliar.github.io/master/pic/2016/Screenshot20160824195821.png

and this is original:

https://raw.githubusercontent.com/fliar/fliar.github.io/master/pic/2016/Screenshot20160824200347.png

**Pull request closed without merging**
