### PR TITLE
Removed Fontawesome from readtheorg

### PR DESCRIPTION
**Pull request by ayys**
This merge fixes issue #77

Remove fontawesome and it's mentions from readtheorg theme

### CODE REVIEW

**Comment by fniessen** [comment]
I don't remember whether this was really needed or not. Certainly something coming from the original theme, but does not mean it is required…
Thanks for this fix!

**Comment by jonathn** [comment]
I think this fix broke the icons that are displayed in admonition titles.
It removed the unnecessary `@font-face{ }` definition,
but also removed the necessary `font-family: FontAwesome;` definitions
required to display `content: "";` correctly.
(I just see a square box instead of a circled exclamation point)

**Comment by s-degoul** [comment]
In fact, Font Awesome seems to be loaded by directive "@import url()" in styles/readtheorg/readtheorg.org line 25.
But, according to syntax of @import (e.g. here: https://developer.mozilla.org/en-US/docs/Web/CSS/@import), provided url should be quoted. It's not in present version.
I locally solved bugs in icons' display (in Firefox 68.11.0esr & Chromium 83.0.4103.116 browsers) by adding quotes like this:
@import url("https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic|Roboto+Slab:400,700|Inconsolata:400,700"); /* not sure for this url */
@import url("https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css");

Should I submit a merge request (I've never done such a thing before)?

**Comment by fniessen** [comment]
Dear @s-degoul , I've just pushed a fix for this (mentioning you - thanks a  lot for that!).

Please tell me if this could be closed.

**Comment by s-degoul** [comment]
Actually, this correction was not enough and I've found other issues.
I'll propose a merge request as soon as possible.

**Pull request merged**
