### PR TITLE
add descriptions on the local mode for readtheorg.

### PR DESCRIPTION
**Pull request by daddygongon**
Thanks for supplying pretty forms of html output from org.  Those are really helpful and convenient.
BTW,  I am often edit orgs on the train without net.  Such a situtaion, the local mode is useful.
I added some descriptions in README.org on the local mode setups for readtheorg.
I will be very happy if you would include my pull request.

### CODE REVIEW

**Comment by nico202** [comment]
Hi! I appreciate it (is what I do, too). But IMHO we should not have local + local2 files. Local just means local, I don't know what was the reason behind having remote resources in the local file; I'd just go fully-offline in the local one :)

**Comment by fniessen** [comment]
Hello all, I do tend to agree with nico202.

daddygongon, could you rewrite a patch in that spirit?  I'll gladly add it to the repo!

**Comment by daddygongon** [comment]
Hi.  Thanks for the fast and kind responces.  In the 'theme-readtheorg-local.setup' in the setup dir, two sites of 'jquery' and 'bootstrap' are directed to https.  Those are failed to be read if you cannot access there via internet or from the cache.  In this case, the final html is made in plain format.  

In my PC, those two javascripts of 'jquery' and 'bootstrap' have been already installed via 'anaconda 3'.  I revise the setup file for directing them
``` org
#+HTML_HEAD: <script src="~/anaconda3/lib/python3.6/site-packages/notebook/static/components/jquery/jquery.min.js"></script>
#+HTML_HEAD: <script src="~/anaconda3/lib/python3.6/site-packages/notebook/static/components/bootstrap/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="~/org-html-themes/styles/lib/js/jquery.stickytableheaders.min.js"></script>
```
 and make '#+SETUPFILE' directing the local setup file.

Does this description make sense?

BTW, can I get the 'highlighted' codes by 'readtheorg'?

**Comment by nico202** [comment]
@fniessen can we add the scripts directly in styles/lib/js right?

**Comment by daddygongon** [comment]
Sure.  I've done them.  

Still, I can't find out a good way to include `highlight.js`

**Comment by fniessen** [comment]
Just have a couple of minutes now. @nico, thanks for helping.

@daddygongon, yes, please try to make a request where there's nothing more private -- no things relevant only to you. Many thanks in advance!

**Comment by fniessen** [comment]
@daddygongon I'm still interested by improvements, if you want to share. Thanks in advance!

**Comment by fniessen** [comment]
Closed by pr/96

**Pull request closed without merging**
